markdown: redcarpet  
permalink: /:title/
url: http://imvincent.github.io
name: imvincent
author: Vincent Zhao
qq: 79673904
email: zhao.qinlong@gmail.com
duoshuo: imvincent
beian: 沪ICP备78542698号
cnzz: 1253417907
weibo: 1676900235
github: imvincent
highlighter: pygments
safe: true
paginate: 20
about: "这里是 Vincent 的个人博客，创建于 2004 年。开始使用了 ExBlog 博客程序；之后长期（2004 ~ 2011）使用 Bo-Blog；2012 年更换为 WordProess；2013年7月迁移到 imvincent @ GitHub。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
